"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,ba,ca;aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;ca=function(a,b){if(b){var c=ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}};
ca("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});ca("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}});_.da=_.da||{};_.l=this;_.ea="closure_uid_"+(1E9*Math.random()>>>0);_.fa=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var qa,ra;_.m=function(a){return void 0!==a};_.p=function(a){return"string"==typeof a};_.ha=function(a){return"number"==typeof a};_.ia=function(a){a=a.split(".");for(var b=_.l,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};_.ja=function(){};
_.ka=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.la=function(a){return"array"==_.ka(a)};_.ma=function(a){var b=_.ka(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.na=function(a){return"function"==_.ka(a)};_.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};qa=function(a,b,c){return a.call.apply(a.bind,arguments)};
ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.q=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.q=qa:_.q=ra;return _.q.apply(null,arguments)};
_.sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.ta=function(a,b){a=a.split(".");var c=_.l;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.m(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}};
_.r=function(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ic=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.ua=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ua);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.r(_.ua,Error);_.ua.prototype.name="CustomError";var va;va=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(_.p(a))return _.p(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.wa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=_.p(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d};_.xa=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=_.p(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};
_.ya=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Aa=function(a,b){b=_.za(a,b,void 0);return 0>b?null:_.p(a)?a.charAt(b):a[b]};_.za=function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.Ba=function(a,b){return 0<=va(a,b)};_.Da=function(a,b){b=va(a,b);var c;(c=0<=b)&&_.Ca(a,b);return c}; _.Ca=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Ea=function(a){return Array.prototype.concat.apply([],arguments)};_.Fa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Ka;_.Ga=function(a,b){return 0==a.lastIndexOf(b,0)};_.Ha=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ia=function(a){return/^[\s\xa0]*$/.test(a)};_.Ja=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.La=function(a,b){var c=0;a=(0,_.Ja)(String(a)).split(".");b=(0,_.Ja)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=Ka(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||Ka(0==f[2].length,0==g[2].length)||Ka(f[2],g[2]);f=f[3];g=g[3]}while(0==c)}return c}; Ka=function(a,b){return a<b?-1:a>b?1:0};
var Ma;Ma=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Na=function(a){return null==a?"":String(a)};a:{var Pa=_.l.navigator;if(Pa){var Qa=Pa.userAgent;if(Qa){_.Oa=Qa;break a}}_.Oa=""}_.v=function(a){return-1!=_.Oa.indexOf(a)};var Sa,Ua;_.Ra=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Sa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Ta=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Ua="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Va=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ua.length;f++)c=Ua[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Wa=function(){return _.v("Trident")||_.v("MSIE")};_.Xa=function(){return _.v("Firefox")||_.v("FxiOS")};_.Za=function(){return _.v("Safari")&&!(_.Ya()||_.v("Coast")||_.v("Opera")||_.v("Edge")||_.Xa()||_.v("Silk")||_.v("Android"))};_.Ya=function(){return(_.v("Chrome")||_.v("CriOS"))&&!_.v("Edge")};
var $a,ab;$a=function(){return _.v("iPhone")&&!_.v("iPod")&&!_.v("iPad")};ab=function(){return $a()||_.v("iPad")||_.v("iPod")};_.bb=function(){return _.v("Macintosh")};_.cb=function(){return _.v("Windows")};_.db=function(){return _.v("CrOS")};var fb=function(a){fb[" "](a);return a};fb[" "]=_.ja;_.gb=function(a,b){try{return fb(a[b]),!0}catch(c){}return!1};_.hb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var ib,kb,ob,rb,sb,wb,xb,zb;ib=_.v("Opera");_.jb=_.Wa();kb=_.v("Edge");_.lb=_.v("Gecko")&&!(-1!=_.Oa.toLowerCase().indexOf("webkit")&&!_.v("Edge"))&&!(_.v("Trident")||_.v("MSIE"))&&!_.v("Edge");_.mb=-1!=_.Oa.toLowerCase().indexOf("webkit")&&!_.v("Edge");ob=_.l.navigator||null;_.nb=ob&&ob.platform||"";_.pb=_.bb();_.qb=_.cb();rb=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var tb="",ub=function(){var a=_.Oa;if(_.lb)return/rv:([^\);]+)(\)|;)/.exec(a);if(kb)return/Edge\/([\d\.]+)/.exec(a);if(_.jb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.mb)return/WebKit\/(\S+)/.exec(a);if(ib)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ub&&(tb=ub?ub[1]:"");if(_.jb){var vb=rb();if(null!=vb&&vb>parseFloat(tb)){sb=String(vb);break a}}sb=tb}wb=sb;xb={};_.yb=function(a){return _.hb(xb,a,function(){return 0<=_.La(wb,a)})};var Ab=_.l.document; zb=Ab&&_.jb?rb()||("CSS1Compat"==Ab.compatMode?parseInt(wb,10):5):void 0;
var Bb=_.Xa(),Cb=$a()||_.v("iPod"),Db=_.v("iPad"),Eb=_.v("Android")&&!(_.Ya()||_.Xa()||_.v("Opera")||_.v("Silk")),Fb=_.Ya(),Gb=_.Za()&&!ab();var Hb=null;var Kb,Mb;_.w=function(){};_.Ib="function"==typeof Uint8Array;
_.A=function(a,b,c,d,e){a.a=null;b||(b=c?[c]:[]);a.l=c?String(c):void 0;a.g=0===c?-1:0;a.b=b;a:{if(b=a.b.length)if(--b,c=a.b[b],!(null===c||"object"!=typeof c||_.la(c)||_.Ib&&c instanceof Uint8Array)){a.h=b-a.g;a.c=c;break a}a.h=Number.MAX_VALUE}a.j={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.h?(c+=a.g,a.b[c]=a.b[c]||_.Jb):(Kb(a),a.c[c]=a.c[c]||_.Jb);if(e&&e.length)for(b=0;b<e.length;b++){c=d=void 0;for(var f=a,g=e[b],k=0;k<g.length;k++){var n=g[k],t=_.y(f,n);null!=t&&(c=n,d=t,_.z(f,n,void 0))}c&&_.z(f,
c,d)}};_.Jb=[];Kb=function(a){var b=a.h+a.g;a.b[b]||(a.c=a.b[b]={})};_.y=function(a,b){if(b<a.h){b+=a.g;var c=a.b[b];return c===_.Jb?a.b[b]=[]:c}if(a.c)return c=a.c[b],c===_.Jb?a.c[b]=[]:c};_.B=function(a,b){a=_.y(a,b);return null==a?a:!!a};_.Lb=function(a,b,c){a=_.y(a,b);return null==a?c:a};_.z=function(a,b,c){b<a.h?a.b[b+a.g]=c:(Kb(a),a.c[b]=c)};_.C=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};
_.E=function(a,b,c){a.a||(a.a={});var d=c?_.D(c):c;a.a[b]=c;_.z(a,b,d)};Mb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(_.la(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){Mb(a);return a.b};
_.w.prototype.C=_.Ib?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){if(!Hb){Hb={};for(var a=0;65>a;a++)Hb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=Hb;for(var c=[],d=0;d<this.length;d+=3){var e=this[d],f=d+1<this.length,g=f?this[d+1]:0,k=d+2<this.length,n=k?this[d+2]:0,t=e>>2;e=(e&3)<<4|g>>4;g=(g&15)<<2|n>>6;n&=63;k||(n=64,f||(g=64));c.push(a[t],a[e],a[g],a[n])}return c.join("")};try{return JSON.stringify(this.b&&_.D(this),
Nb)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.b&&_.D(this),Nb)};var Nb=function(a,b){return _.ha(b)&&(isNaN(b)||Infinity===b||-Infinity===b)?String(b):b};_.w.prototype.toString=function(){Mb(this);return this.b.toString()};
_.F=function(){this.G=this.G;this.C=this.C};_.F.prototype.G=!1;_.F.prototype.$=function(){this.G||(this.G=!0,this.v())};_.I=function(a,b){_.G(a,_.sa(_.H,b))};_.G=function(a,b,c){a.G?_.m(c)?b.call(c):b():(a.C||(a.C=[]),a.C.push(_.m(c)?(0,_.q)(b,c):b))};_.F.prototype.v=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.H=function(a){a&&"function"==typeof a.$&&a.$()};
var Ob=function(a,b){this.g=a;this.c=b;this.b=0;this.a=null};Ob.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.g();return a};var Pb=function(a,b){a.c(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};var Tb;_.Qb=[];_.Rb=[];_.Sb=!1;Tb=function(a){_.Qb[_.Qb.length]=a;if(_.Sb)for(var b=0;b<_.Rb.length;b++)a((0,_.q)(_.Rb[b].b,_.Rb[b]))};var Ub,Wb,Xb,Vb;Ub=function(a){_.l.setTimeout(function(){throw a;},0)};_.Yb=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));c=Vb(c);!_.na(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.v("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Wb||(Wb=Xb()),Wb(c)):_.l.setImmediate(c)};
Xb=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.v("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=(0,_.q)(function(a){if(("*"==d||a.origin==d)&&
a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.Wa()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.qb;c.qb=null;a()}};return function(a){d.next={qb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");b.onreadystatechange= function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};Vb=function(a){return a};Tb(function(a){Vb=a});
var Zb=function(){this.b=this.a=null},ac=new Ob(function(){return new $b},function(a){a.reset()});Zb.prototype.add=function(a,b){var c=ac.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};Zb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var $b=function(){this.next=this.b=this.a=null};$b.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};$b.prototype.reset=function(){this.next=this.b=this.a=null};
var fc=function(a,b){bc||cc();dc||(bc(),dc=!0);ec.add(a,b)},bc,cc=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);bc=function(){a.then(gc)}}else bc=function(){_.Yb(gc)}},dc=!1,ec=new Zb,gc=function(){for(var a;a=ec.remove();){try{a.a.call(a.b)}catch(b){Ub(b)}Pb(ac,a)}dc=!1};
var hc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var kc,lc,mc,rc,vc,wc,uc,sc;_.jc=function(a){this.a=0;this.j=void 0;this.c=this.b=this.g=null;this.h=this.C=!1;if(a!=_.ja)try{var b=this;a.call(void 0,function(a){_.ic(b,2,a)},function(a){_.ic(b,3,a)})}catch(c){_.ic(this,3,c)}};kc=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};kc.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};lc=new Ob(function(){return new kc},function(a){a.reset()});mc=function(a,b,c){var d=lc.get();d.h=a;d.b=b;d.c=c;return d};
_.oc=function(){var a,b=new _.jc(function(b){a=b});return new nc(b,a)};_.jc.prototype.then=function(a,b,c){return _.pc(this,_.na(a)?a:null,_.na(b)?b:null,c)};_.jc.prototype.$goog_Thenable=!0;_.jc.prototype.cancel=function(a){0==this.a&&fc(function(){var b=new qc(a);rc(this,b)},this)};
rc=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.g||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?rc(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):sc(c),tc(c,e,3,b)))}a.g=null}else _.ic(a,3,b)};vc=function(a,b){a.b||2!=a.a&&3!=a.a||uc(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.pc=function(a,b,c,d){var e=mc(null,null,null);e.a=new _.jc(function(a,g){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(t){g(t)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof qc?g(b):a(e)}catch(t){g(t)}}:g});e.a.g=a;vc(a,e);return e.a};_.jc.prototype.m=function(a){this.a=0;_.ic(this,2,a)};_.jc.prototype.o=function(a){this.a=0;_.ic(this,3,a)};
_.ic=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("d"));a.a=1;a:{var d=c,e=a.m,f=a.o;if(d instanceof _.jc){vc(d,mc(e||_.ja,f||null,a));var g=!0}else if(hc(d))d.then(e,f,a),g=!0;else{if(_.oa(d))try{var k=d.then;if(_.na(k)){wc(d,k,e,f,a);g=!0;break a}}catch(n){f.call(a,n);g=!0;break a}g=!1}}g||(a.j=c,a.a=b,a.g=null,uc(a),3!=b||c instanceof qc||xc(a,c))}};wc=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,g,k)}catch(n){k(n)}};
uc=function(a){a.C||(a.C=!0,fc(a.l,a))};sc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.jc.prototype.l=function(){for(var a;a=sc(this);)tc(this,a,this.a,this.j);this.C=!1};
var tc=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,yc(b,c,d);else try{b.g?b.h.call(b.c):yc(b,c,d)}catch(e){zc.call(null,e)}Pb(lc,b)},yc=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},xc=function(a,b){a.h=!0;fc(function(){a.h&&zc.call(null,b)})},zc=Ub,qc=function(a){_.ua.call(this,a)};_.r(qc,_.ua);qc.prototype.name="cancel";var nc=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Ac=function(a){this.l=[];this.D=a;this.C=this.c=!1;this.h=void 0;this.F=this.M=this.o=!1;this.m=0;this.a=null;this.j=0};_.Ac.prototype.cancel=function(a){if(this.c)this.h instanceof _.Ac&&this.h.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.j--,0>=b.j&&b.cancel())}this.D?this.D.call(null,this):this.F=!0;this.c||this.A(new _.Bc(this))}};_.Ac.prototype.I=function(a,b){this.o=!1;Cc(this,a,b)};
var Cc=function(a,b,c){a.c=!0;a.h=c;a.C=!b;Dc(a)},Fc=function(a){if(a.c){if(!a.F)throw new Ec(a);a.F=!1}};_.Ac.prototype.g=function(a){Fc(this);Cc(this,!0,a)};_.Ac.prototype.A=function(a){Fc(this);Cc(this,!1,a)};_.Hc=function(a,b,c){_.Gc(a,b,null,c)};_.Gc=function(a,b,c,d){a.l.push([b,c,d]);a.c&&Dc(a)};_.Ac.prototype.then=function(a,b,c){var d,e,f=new _.jc(function(a,b){d=a;e=b});_.Gc(this,d,function(a){a instanceof _.Bc?f.cancel():e(a)});return f.then(a,b,c)};_.Ac.prototype.$goog_Thenable=!0;
_.Ac.prototype.b=function(a){var b=new _.Ac;_.Gc(this,b.g,b.A,b);a&&(b.a=this,this.j++);return b};_.Ac.prototype.isError=function(a){return a instanceof Error};
var Ic=function(a){return(0,_.ya)(a.l,function(a){return _.na(a[1])})},Dc=function(a){if(a.m&&a.c&&Ic(a)){var b=a.m,c=Jc[b];c&&(_.l.clearTimeout(c.a),delete Jc[b]);a.m=0}a.a&&(a.a.j--,delete a.a);b=a.h;for(var d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],g=e[1];e=e[2];if(f=a.C?g:f)try{var k=f.call(e||null,b);_.m(k)&&(a.C=a.C&&(k==b||a.isError(k)),a.h=b=k);if(hc(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.o=!0}catch(n){b=n,a.C=!0,Ic(a)||(c=!0)}}a.h=b;d&&(k=(0,_.q)(a.I,
a,!0),d=(0,_.q)(a.I,a,!1),b instanceof _.Ac?(_.Gc(b,k,d),b.M=!0):b.then(k,d));c&&(b=new Kc(b),Jc[b.a]=b,a.m=b.a)},Ec=function(){_.ua.call(this)};_.r(Ec,_.ua);Ec.prototype.message="Deferred has already fired";Ec.prototype.name="AlreadyCalledError";_.Bc=function(){_.ua.call(this)};_.r(_.Bc,_.ua);_.Bc.prototype.message="Deferred was canceled";_.Bc.prototype.name="CanceledError";var Kc=function(a){this.a=_.l.setTimeout((0,_.q)(this.g,this),0);this.b=a}; Kc.prototype.g=function(){delete Jc[this.a];throw this.b;};var Jc={};
var Lc=!_.lb&&!_.jb||_.jb&&9<=Number(zb)||_.lb&&_.yb("1.9.1");_.Mc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.Oc=function(){this.b="";this.g=_.Nc};_.Oc.prototype.Ca=!0;_.Oc.prototype.za=function(){return this.b};_.Oc.prototype.jb=!0;_.Oc.prototype.a=function(){return 1};_.Nc={};_.Pc=function(a){var b=new _.Oc;b.b=a;return b};_.Pc("about:blank");_.Rc=function(){this.b="";this.c=_.Qc;this.g=null};_.Rc.prototype.jb=!0;_.Rc.prototype.a=function(){return this.g};_.Rc.prototype.Ca=!0;_.Rc.prototype.za=function(){return this.b};_.Qc={};_.Sc=function(a,b){var c=new _.Rc;c.b=a;c.g=b;return c};_.Sc("<!DOCTYPE html>",0);_.Sc("",0);_.Tc=_.Sc("<br>",0);
_.Uc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div");a.innerHTML="<div><div></div></div>";var b=a.firstChild.firstChild;a.innerHTML="";return!b.parentElement});var Xc;_.Wc=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Vc(c,"*",a,b)[0]||null}return a||null};
_.Vc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,g;g=a[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;g=a[f];f++)b=g.className,"function"==typeof b.split&&_.Ba(b.split(/\s+/),c)&&(d[e++]=g);d.length=e;return d}return a};
_.Yc=function(a,b){_.Ra(b,function(b,d){b&&"object"==typeof b&&b.Ca&&(b=b.za());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Xc.hasOwnProperty(d)?a.setAttribute(Xc[d],b):_.Ga(d,"aria-")||_.Ga(d,"data-")?a.setAttribute(d,b):a[d]=b})};Xc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Zc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.$c=function(a){this.a=a||_.l.document||document};_.$c.prototype.B=function(a){return _.p(a)?this.a.getElementById(a):a};_.$c.prototype.setProperties=_.Yc;_.ad=function(a,b){return a.a.createElement(String(b))};_.$c.prototype.getChildren=function(a){return Lc&&void 0!=a.children?a.children:(0,_.wa)(a.childNodes,function(a){return 1==a.nodeType})};
_.$c.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var cd,bd,fd,gd,ed;_.dd=function(a){var b=[];bd(new cd,a,b);return b.join("")};cd=function(){};
bd=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.la(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),bd(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),ed(d,c),c.push(":"),bd(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":ed(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("e`"+typeof b);}}};fd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};gd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;ed=function(a,b){b.push('"',a.replace(gd,function(a){var b=fd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),fd[a]=b);return b}),'"')};
var hd="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""},id=function(){};id.prototype.next=function(){throw hd;};id.prototype.ha=function(){return this};
var jd=function(a){if(a instanceof id)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.ma(a)){var b=0,c=new id;c.next=function(){for(;;){if(b>=a.length)throw hd;if(b in a)return a[b++];b++}};return c}throw Error("f");},kd=function(a,b){if(_.ma(a))try{(0,_.u)(a,b,void 0)}catch(c){if(c!==hd)throw c;}else{a=jd(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==hd)throw c;}}},ld=function(a){if(_.ma(a))return _.Fa(a);a=jd(a);var b=[];kd(a,function(a){b.push(a)});return b};
_.J=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof _.J)for(c=a.X(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};_.J.prototype.S=function(){md(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.J.prototype.X=function(){md(this);return this.a.concat()};_.od=function(a,b){return nd(a.b,b)};
_.J.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.J.prototype.remove=function(a){return nd(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&md(this),!0):!1};var md=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];nd(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],nd(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.J.prototype.get=function(a,b){return nd(this.b,a)?this.b[a]:b};
_.J.prototype.set=function(a,b){nd(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.J.prototype.forEach=function(a,b){for(var c=this.X(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.J.prototype.ha=function(a){md(this);var b=0,c=this.c,d=this,e=new id;e.next=function(){if(c!=d.c)throw Error("g");if(b>=d.a.length)throw hd;var e=d.a[b++];return a?e:d.b[e]};return e};var nd=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.K=function(a,b){this.type="undefined"!=typeof _.pd&&a instanceof _.pd?String(a):a;this.b=this.target=b;this.c=!1;this.wb=!0};_.K.prototype.h=function(){this.c=!0};_.K.prototype.g=function(){this.wb=!1};var qd=!_.jb||9<=Number(zb),rd=_.jb&&!_.yb("9"),sd=function(){if(!_.l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.l.addEventListener("test",_.ja,b),_.l.removeEventListener("test",_.ja,b)}catch(c){}return a}();
var ud=function(a,b){_.K.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;(b=a.relatedTarget)?_.lb&&(_.gb(b,"nodeName")||(b=null)):"mouseover"==c?
b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=_.p(a.pointerType)?a.pointerType:td[a.pointerType]||"";this.a=a;a.defaultPrevented&&this.g()}};_.r(ud,_.K);var td={2:"touch",3:"pen",4:"mouse"};ud.prototype.h=function(){ud.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0}; ud.prototype.g=function(){ud.w.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,rd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var vd,xd;vd="closure_listenable_"+(1E6*Math.random()|0);_.wd=function(a){return!(!a||!a[vd])};xd=0;var yd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Ma=e;this.key=++xd;this.removed=this.Ka=!1},zd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ma=null};var Ad=function(a){this.src=a;this.a={};this.b=0},Ed,Bd;Ad.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Bd(a,b,d,e);-1<g?(b=a[g],c||(b.Ka=!1)):(b=new yd(b,this.src,f,!!d,e),b.Ka=c,a.push(b));return b};Ad.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Bd(e,b,c,d);return-1<b?(zd(e[b]),_.Ca(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Cd=function(a,b){var c=b.type;c in a.a&&_.Da(a.a[c],b)&&(zd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Ad.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,zd(d[e]);delete this.a[c];this.b--}return b};_.Dd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Bd(a,c,d,e));return-1<b?a[b]:null};
Ed=function(a){var b=_.m(void 0)?"undefined":void 0,c=_.m(b),d=c?b.toString():"",e=_.m(void 0);return Sa(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})};Bd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Ma==d)return e}return-1};
var Fd,Gd,Hd,Ld,Nd,Od,Td,Sd,Pd,Ud;Fd="closure_lm_"+(1E6*Math.random()|0);Gd={};Hd=0;_.Jd=function(a,b,c,d,e){if(d&&d.once)return _.Id(a,b,c,d,e);if(_.la(b)){for(var f=0;f<b.length;f++)_.Jd(a,b[f],c,d,e);return null}c=_.Kd(c);return _.wd(a)?a.listen(b,c,_.oa(d)?!!d.capture:!!d,e):Ld(a,b,c,!1,d,e)};
Ld=function(a,b,c,d,e,f){if(!b)throw Error("h");var g=_.oa(e)?!!e.capture:!!e,k=_.Md(a);k||(a[Fd]=k=new Ad(a));c=k.add(b,c,d,g,f);if(c.proxy)return c;d=Nd();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)sd||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Od(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("i");Hd++;return c};
Nd=function(){var a=Pd,b=qd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};_.Id=function(a,b,c,d,e){if(_.la(b)){for(var f=0;f<b.length;f++)_.Id(a,b[f],c,d,e);return null}c=_.Kd(c);return _.wd(a)?a.M(b,c,_.oa(d)?!!d.capture:!!d,e):Ld(a,b,c,!0,d,e)};
_.Qd=function(a,b,c,d,e){if(_.la(b))for(var f=0;f<b.length;f++)_.Qd(a,b[f],c,d,e);else d=_.oa(d)?!!d.capture:!!d,c=_.Kd(c),_.wd(a)?a.g.remove(String(b),c,d,e):a&&(a=_.Md(a))&&(b=_.Dd(a,b,c,d,e))&&_.Rd(b)};
_.Rd=function(a){if(!_.ha(a)&&a&&!a.removed){var b=a.src;if(_.wd(b))Cd(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Od(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Hd--;(c=_.Md(b))?(Cd(c,a),0==c.b&&(c.src=null,b[Fd]=null)):zd(a)}}};Od=function(a){return a in Gd?Gd[a]:Gd[a]="on"+a};
Td=function(a,b,c,d){var e=!0;if(a=_.Md(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=Sd(f,d),e=e&&!1!==f)}return e};Sd=function(a,b){var c=a.listener,d=a.Ma||a.src;a.Ka&&_.Rd(a);return c.call(d,b)};
Pd=function(a,b){if(a.removed)return!0;if(!qd){var c=b||_.ia("window.event");b=new ud(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.b=c[e];var f=Td(c[e],a,!0,b);d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.b=c[e],f=Td(c[e],a,!1,b),d=d&&f}return d}return Sd(a,new ud(b,this))}; _.Md=function(a){a=a[Fd];return a instanceof Ad?a:null};Ud="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Kd=function(a){if(_.na(a))return a;a[Ud]||(a[Ud]=function(b){return a.handleEvent(b)});return a[Ud]};Tb(function(a){Pd=a(Pd)});
_.L=function(){_.F.call(this);this.g=new Ad(this);this.ga=this;this.F=null};_.r(_.L,_.F);_.L.prototype[vd]=!0;_.L.prototype.I=function(a){this.F=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.Qd(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.ga;d=b.type||b;if(_.p(b))b=new _.K(b,a);else if(b instanceof _.K)b.target=b.target||a;else{var e=b;b=new _.K(d,a);_.Va(b,e)}e=!0;if(c)for(var f=c.length-1;!b.c&&0<=f;f--){var g=b.b=c[f];e=g.na(d,!0,b)&&e}b.c||(g=b.b=a,e=g.na(d,!0,b)&&e,b.c||(e=g.na(d,!1,b)&&e));if(c)for(f=0;!b.c&&f<c.length;f++)g=b.b=c[f],e=g.na(d,!1,b)&&e;return e};_.L.prototype.v=function(){_.L.w.v.call(this);this.g&&this.g.removeAll(void 0);this.F=null};
_.L.prototype.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};_.L.prototype.M=function(a,b,c,d){return this.g.add(String(a),b,!0,c,d)};_.L.prototype.na=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var g=f.listener,k=f.Ma||f.src;f.Ka&&Cd(this.g,f);d=!1!==g.call(k,c)&&d}}return d&&0!=c.wb};
var Vd=function(){};Vd.prototype.a=null;var Xd=function(a){var b;(b=a.a)||(b={},Wd(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Yd,Zd=function(){};_.r(Zd,Vd);var $d=function(a){return(a=Wd(a))?new ActiveXObject(a):new XMLHttpRequest},Wd=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("j");}return a.b};Yd=new Zd;
var be;_.ae=function(a){if(a.S&&"function"==typeof a.S)return a.S();if(_.p(a))return a.split("");if(_.ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};
be=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ma(a)||_.p(a))(0,_.u)(a,b,void 0);else{if(a.X&&"function"==typeof a.X)var c=a.X();else if(a.S&&"function"==typeof a.S)c=void 0;else if(_.ma(a)||_.p(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]=e;d=_.ae(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
_.ce=function(a,b){_.L.call(this);this.b=a||1;this.a=b||_.l;this.c=(0,_.q)(this.kc,this);this.h=(0,_.fa)()};_.r(_.ce,_.L);_.h=_.ce.prototype;_.h.pa=!1;_.h.Y=null;_.h.setInterval=function(a){this.b=a;this.Y&&this.pa?(this.stop(),this.start()):this.Y&&this.stop()};_.h.kc=function(){if(this.pa){var a=(0,_.fa)()-this.h;0<a&&a<.8*this.b?this.Y=this.a.setTimeout(this.c,this.b-a):(this.Y&&(this.a.clearTimeout(this.Y),this.Y=null),_.M(this,"tick"),this.pa&&(this.stop(),this.start()))}};
_.h.start=function(){this.pa=!0;this.Y||(this.Y=this.a.setTimeout(this.c,this.b),this.h=(0,_.fa)())};_.h.stop=function(){this.pa=!1;this.Y&&(this.a.clearTimeout(this.Y),this.Y=null)};_.h.v=function(){_.ce.w.v.call(this);this.stop();delete this.a};_.de=function(a,b,c){if(_.na(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("k");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};_.ee=function(a){_.l.clearTimeout(a)};
var fe=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ge=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var he=function(a){_.L.call(this);this.headers=new _.J;this.o=a||null;this.b=!1;this.m=this.a=null;this.K="";this.c=this.D=this.h=this.A=!1;this.l=0;this.j=null;this.W="";this.P=this.N=!1},ie,je,ke,se,re,oe,te;_.r(he,_.L);ie=/^https?$/i;je=["POST","PUT"];ke=[];_.le=function(a,b,c,d,e,f,g){var k=new he;ke.push(k);b&&k.listen("complete",b);k.M("ready",k.ba);f&&(k.l=Math.max(0,f));g&&(k.N=g);k.send(a,c,d,e)};he.prototype.ba=function(){this.$();_.Da(ke,this)};
he.prototype.send=function(a,b,c,d){if(this.a)throw Error("l`"+this.K+"`"+a);b=b?b.toUpperCase():"GET";this.K=a;this.A=!1;this.b=!0;this.a=this.o?$d(this.o):$d(Yd);this.m=this.o?Xd(this.o):Xd(Yd);this.a.onreadystatechange=(0,_.q)(this.V,this);try{this.D=!0,this.a.open(b,String(a),!0),this.D=!1}catch(f){me(this);return}a=c||"";var e=new _.J(this.headers);d&&be(d,function(a,b){e.set(b,a)});d=_.Aa(e.X(),ne);c=_.l.FormData&&a instanceof _.l.FormData;!_.Ba(je,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.W&&(this.a.responseType=this.W);"withCredentials"in this.a&&this.a.withCredentials!==this.N&&(this.a.withCredentials=this.N);try{oe(this),0<this.l&&((this.P=pe(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.q)(this.T,this)):this.j=_.de(this.T,this.l,this)),this.h=!0,this.a.send(a),this.h=!1}catch(f){me(this)}};var pe=function(a){return _.jb&&_.yb(9)&&_.ha(a.timeout)&&_.m(a.ontimeout)},ne=function(a){return"content-type"==a.toLowerCase()};
he.prototype.T=function(){"undefined"!=typeof _.da&&this.a&&(_.M(this,"timeout"),this.abort(8))};var me=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);qe(a);re(a)},qe=function(a){a.A||(a.A=!0,_.M(a,"complete"),_.M(a,"error"))};he.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.M(this,"complete"),_.M(this,"abort"),re(this))};he.prototype.v=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),re(this,!0));he.w.v.call(this)};
he.prototype.V=function(){this.G||(this.D||this.h||this.c?se(this):this.L())};he.prototype.L=function(){se(this)};se=function(a){if(a.b&&"undefined"!=typeof _.da&&(!a.m[1]||4!=(a.a?a.a.readyState:0)||2!=te(a)))if(a.h&&4==(a.a?a.a.readyState:0))_.de(a.V,0,a);else if(_.M(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.ue(a)?(_.M(a,"complete"),_.M(a,"success")):qe(a)}finally{re(a)}}};
re=function(a,b){if(a.a){oe(a);var c=a.a,d=a.m[0]?_.ja:null;a.a=null;a.m=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};oe=function(a){a.a&&a.P&&(a.a.ontimeout=null);a.j&&(_.ee(a.j),a.j=null)};
_.ue=function(a){var b=te(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.K).match(fe)[1]||null,!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!ie.test(a?a.toLowerCase():"");c=b}return c};te=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};Tb(function(a){he.prototype.L=a(he.prototype.L)});
var we;_.N=function(a){_.F.call(this);this.P=a;this.o={}};_.r(_.N,_.F);var ve=[];_.N.prototype.listen=function(a,b,c,d){_.la(b)||(b&&(ve[0]=b.toString()),b=ve);for(var e=0;e<b.length;e++){var f=_.Jd(a,b[e],c||this.handleEvent,d||!1,this.P||this);if(!f)break;this.o[f.key]=f}return this};_.xe=function(a,b,c,d){we(a,b,c,d,void 0)};we=function(a,b,c,d,e,f){if(_.la(c))for(var g=0;g<c.length;g++)we(a,b,c[g],d,e,f);else(b=_.Id(b,c,d||a.handleEvent,e,f||a.P||a))&&(a.o[b.key]=b)}; _.N.prototype.removeAll=function(){_.Ra(this.o,function(a,b){this.o.hasOwnProperty(b)&&_.Rd(a)},this);this.o={}};_.N.prototype.v=function(){_.N.w.v.call(this);this.removeAll()};_.N.prototype.handleEvent=function(){throw Error("m");};
_.ye=function(a){_.A(this,a,0,null,null)};_.r(_.ye,_.w);var Ae=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("n");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,t,x,U){if("%"==t)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("o");arguments[0]=e;return ze[t].apply(null,arguments)})},ze={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Ma(" ",Number(c)-a.length):Ma(" ",Number(c)-a.length)+a},f:function(a,b,c,
d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Ma(" ",a):f+Ma(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,g,k){return ze.f(parseInt(a,10),b,c,d,0,f,g,k)}};ze.i=ze.d;ze.u=ze.d;
_.O=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Ae("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+Ae(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Ae.apply({},c)))};
_.Ce=function(a){_.A(this,a,"h_exts",Be,null)};_.r(_.Ce,_.w);var Be=[2];_.Ce.messageId="h_exts";var De,Ee,Fe,Ie,Ke,Ve,Le,Ne,Me,Qe,Oe,Je,We;_.P=function(a,b){this.b=this.j=this.h="";this.c=null;this.l=this.a="";this.C=!1;var c;a instanceof _.P?(this.C=_.m(b)?b:a.C,De(this,a.h),this.j=a.j,this.b=a.b,Ee(this,a.c),this.a=a.a,Fe(this,Ge(a.g)),_.He(this,a.l)):a&&(c=String(a).match(fe))?(this.C=!!b,De(this,c[1]||"",!0),this.j=Ie(c[2]||""),this.b=Ie(c[3]||"",!0),Ee(this,c[4]),this.a=Ie(c[5]||"",!0),Fe(this,c[6]||"",!0),_.He(this,c[7]||"",!0)):(this.C=!!b,this.g=new Je(null,this.C))};
_.P.prototype.toString=function(){var a=[],b=this.h;b&&a.push(Ke(b,Le,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Ke(b,Le,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Ke(c,"/"==c.charAt(0)?Me:Ne,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Ke(c,Oe));return a.join("")};
De=function(a,b,c){a.h=c?Ie(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};Ee=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("p`"+b);a.c=b}else a.c=null};Fe=function(a,b,c){b instanceof Je?(a.g=b,Pe(a.g,a.C)):(c||(b=Ke(b,Qe)),a.g=new Je(b,a.C))};_.Q=function(a,b,c){a.g.set(b,c)};_.He=function(a,b,c){a.l=c?Ie(b):b};_.Te=function(a){return a instanceof _.P?new _.P(a):new _.P(a,void 0)};
_.Ue=function(a,b){a instanceof _.P||(a=_.Te(a));b instanceof _.P||(b=_.Te(b));var c=a;a=new _.P(c);var d=!!b.h;d?De(a,b.h):d=!!b.j;d?a.j=b.j:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)Ee(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){c=_.Ga(e,"/");e=e.split("/");for(var f=[],g=0;g<e.length;){var k=e[g++];"."==k?c&&g==e.length&&f.push(""):".."==k?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&g==e.length&&f.push("")):(f.push(k),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?Fe(a,Ge(b.g)):d=!!b.l;d&&_.He(a,b.l);return a};Ie=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""};Ke=function(a,b,c){return _.p(a)?(a=encodeURI(a).replace(b,Ve),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Ve=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Le=/[#\/\?@]/g;Ne=/[#\?:]/g;Me=/[#\?]/g;
Qe=/[#\?@]/g;Oe=/#/g;Je=function(a,b){this.b=this.a=null;this.g=a||null;this.c=!!b};We=function(a){a.a||(a.a=new _.J,a.b=0,a.g&&ge(a.g,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Je.prototype.add=function(a,b){We(this);this.g=null;a=Xe(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};Je.prototype.remove=function(a){We(this);a=Xe(this,a);return _.od(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};
Je.prototype.clear=function(){this.a=this.g=null;this.b=0};var Ye=function(a,b){We(a);b=Xe(a,b);return _.od(a.a,b)};_.h=Je.prototype;_.h.forEach=function(a,b){We(this);this.a.forEach(function(c,d){(0,_.u)(c,function(c){a.call(b,c,d,this)},this)},this)};_.h.X=function(){We(this);for(var a=this.a.S(),b=this.a.X(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
_.h.S=function(a){We(this);var b=[];if(_.p(a))Ye(this,a)&&(b=_.Ea(b,this.a.get(Xe(this,a))));else{a=this.a.S();for(var c=0;c<a.length;c++)b=_.Ea(b,a[c])}return b};_.h.set=function(a,b){We(this);this.g=null;a=Xe(this,a);Ye(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};_.h.get=function(a,b){if(!a)return b;a=this.S(a);return 0<a.length?String(a[0]):b};_.Ze=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(Xe(a,b),_.Fa(c)),a.b+=c.length)};
Je.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.X(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.S(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.g=a.join("&")};
var Ge=function(a){var b=new Je;b.g=a.g;a.a&&(b.a=new _.J(a.a),b.b=a.b);return b},Xe=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},Pe=function(a,b){b&&!a.c&&(We(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.Ze(this,c,a))},a));a.c=b};
var $e;$e=function(a){return(a=a.exec(_.Oa))?a[1]:""};_.af=function(){if(Bb)return $e(/Firefox\/([0-9.]+)/);if(_.jb||kb||ib)return wb;if(Fb)return ab()?$e(/CriOS\/([0-9.]+)/):$e(/Chrome\/([0-9.]+)/);if(Gb&&!ab())return $e(/Version\/([0-9.]+)/);if(Cb||Db){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Oa);if(a)return a[1]+"."+a[2]}else if(Eb)return(a=$e(/Android\s+([0-9.]+)/))?a:$e(/Version\/([0-9.]+)/);return""}();
var bf=function(a,b){_.K.call(this,a,b);this.U=b};_.r(bf,_.K);var cf=function(a){_.A(this,a,"capi_md1571",null,null)};_.r(cf,_.w);var df=function(a){_.A(this,a,0,null,null)};_.r(df,_.w);cf.messageId="capi_md1571";var ff=function(){for(var a=10,b=ef,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},ef="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.gf=function(a,b){_.F.call(this);this.j=b||ff();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.N(this);_.I(this,this.h);this.h.listen(window,"message",this.m)};_.r(_.gf,_.F);_.gf.prototype.da=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.gf.prototype.m=function(a){a=a.a;var b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.P(b)).b,b=_.Ha(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.p(b)&&"["==b[0]){try{var c=JSON.parse(b);if(!_.la(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new cf(c),_.y(c,1)==this.j)){b=_.y(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.da(a.origin,a.source);1==
_.y(c,2)?this.send(2):this.l(c,a)}}};_.gf.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new cf;_.z(b,3,this.j);_.z(b,1,this.a);_.z(b,2,a);var d=JSON.stringify(_.D(b)),e=this.g,f=this.c;_.jb?_.de(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var hf=function(a,b,c,d){this.g=_.oc();this.a=new _.gf((0,_.q)(this.h,this),c);this.a.da("*",a,d);this.a.a=b;this.b=new _.ce(50);this.b.start();_.Jd(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.C;b=mc(b,b,this);b.g=!0;vc(a,b)};hf.prototype.C=function(){_.H(this.a);_.Qd(this.b,"tick",this.c,!1,this);_.H(this.b)};hf.prototype.c=function(){this.a.send(1)};hf.prototype.h=function(a,b){2==_.y(a,2)&&this.g.b(b.origin)};
var jf=function(a,b,c){_.F.call(this);this.b=a;a=_.y(b,3);b=_.y(b,1);this.a=new _.gf((0,_.q)(this.g,this),b);this.a.a=a;c&&this.a.da(c.origin,c.source);_.I(this,this.a)};_.r(jf,_.F);jf.prototype.send=function(a){var b=new cf;_.E(b,4,a);this.a.send(0,b)};jf.prototype.connect=function(a,b){this.a.da(a,b);this.a.send(3)};jf.prototype.g=function(a){0==_.y(a,2)&&(a=_.C(a,df,4),this.b(a))};jf.prototype.c=_.ja;
var lf=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],kf(this)):(this.a=new _.gf(_.ja,_.y(b,1)),a=_.y(b,3),this.a.a=a)};_.r(lf,_.F);lf.prototype.v=function(){lf.w.v.call(this);this.b&&this.b.close();_.H(this.a)};lf.prototype.c=function(){this.g=new _.N(this);_.I(this,this.g);kf(this)};lf.prototype.send=function(a){this.b.postMessage(_.D(a))};
lf.prototype.connect=function(a,b){var c=new MessageChannel;this.b=c.port1;kf(this);var d=this.a;this.a=null;c=c.port2;d.da(a,b);d.send(4,void 0,[c]);_.H(d)};var kf=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};lf.prototype.j=function(a){a=a.a;try{var b=new df(a.data)}catch(c){return}this.h(b)};
var mf=function(a,b,c){var d=!1;_.m(_.y(b,2))?4==_.y(b,2)&&(d=!0):d=Fb;return d?new lf(a,b,c):new jf(a,b,c)};var rf,tf;_.nf=function(){_.L.call(this);this.j=null;this.l=!1;this.h=[];this.c=[];_.G(this,this.o,this);this.b=null};_.r(_.nf,_.L);_.nf.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.pf=function(a){a.o();a.h=[];a.b=new _.Ac;a.c.push((0,_.q)(a.b.cancel,a.b));a.l=!1;_.Hc(a.b.b(),function(a){(Ed(this.g)||this.F)&&_.of(this);this.c.push(_.sa(_.H,a))},a)};_.nf.prototype.sendMessage=function(a){qf(this,_.D(a))};var qf=function(a,b){if(a.b){var c=new df;_.z(c,1,b);_.Hc(a.b.b(),function(a){a.send(c)})}};
_.nf.prototype.H=function(){return this};_.nf.prototype.da=function(a,b,c){this.a.da(a,b,c)};_.sf=function(a,b,c,d){_.pf(a);rf(a,b,c,d).then(function(a){var d=new cf;_.z(d,1,a.lc);_.z(d,3,c);d=mf((0,_.q)(this.m,this),d);d.connect(a.origin,b);this.b.g(d)},void 0,a)};rf=function(a,b,c,d){var e=ff();b=(new hf(b,c,e,d)).g.a;a.c.push((0,_.q)(b.cancel,b));return b.then(function(a){return{lc:e,origin:a}})};
_.nf.prototype.D=function(a,b){if(3==_.y(a,2)||4==_.y(a,2))_.H(this.a),this.a=null,this.b.g(mf((0,_.q)(this.m,this),a,b))};_.nf.prototype.m=function(a){this.h.push(a);this.A()};_.nf.prototype.A=function(){for(;tf(this););};tf=function(a){if(a.G||!a.l||0==a.h.length)return!1;var b=_.y(a.h.shift(),1);a.j&&qf(a.j,b);_.M(a,new bf(b[0],b));return!0};_.of=function(a){a.l||(a.l=!0,a.b&&_.Hc(a.b.b(),function(a){a.c();_.de(this.A,0,this)},a))}; _.nf.prototype.listen=function(a,b,c,d){_.of(this);return _.nf.w.listen.call(this,a,b,c,d)};_.nf.prototype.M=function(a,b,c,d){_.of(this);return _.nf.w.M.call(this,a,b,c,d)};_.nf.prototype.I=function(a){_.of(this);return _.nf.w.I.call(this,a)};
var uf=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};uf.prototype.ca=function(a){this.c=a;return this};uf.prototype.qa=function(a){this.a=a;return this};uf.prototype.mb=function(a){this.g=_.Ta(a);return this};var vf=function(){};var wf=function(){};_.r(wf,vf);wf.prototype.clear=function(){var a=ld(this.ha(!0)),b=this;(0,_.u)(a,function(a){b.remove(a)})};var xf=function(a){this.a=a};_.r(xf,wf);_.h=xf.prototype;_.h.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.h.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.h.get=function(a){a=this.a.getItem(a);if(!_.p(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.h.remove=function(a){this.a.removeItem(a)};
_.h.ha=function(a){var b=0,c=this.a,d=new id;d.next=function(){if(b>=c.length)throw hd;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.p(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.h.clear=function(){this.a.clear()};_.h.key=function(a){return this.a.key(a)};
var yf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.r(yf,xf);var Af=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new yf);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=JSON.parse(a)||[]}catch(c){}a=!1;_.la(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&zf(this)},zf=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.dd(a.a))}catch(b){}};
var Bf=function(a){_.F.call(this);this.a=a;this.h=!1};_.r(Bf,_.F);Bf.prototype.setEnabled=function(a){this.h=a};var R=function(a){Bf.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.F=!0;this.j=10;this.b=null;this.c=!1};_.r(R,Bf);R.prototype.Ab=function(a){this.F=a;return this};R.prototype.setUseLocalStorage=R.prototype.Ab;R.prototype.jc=function(a){this.j=Math.min(a,100);return this};R.prototype.setMaxErrorsPerHour=R.prototype.jc;R.prototype.yb=function(a){this.o=a;return this};R.prototype.setGlobalSampling=R.prototype.yb;R.prototype.ob=function(a,b){this.m[a]=b;return this};
R.prototype.addPerErrorMessageSampling=R.prototype.ob;R.prototype.xb=function(a){this.O=a;return this};R.prototype.setCallback=R.prototype.xb;R.prototype.ic=function(a){this.g=a;return this};R.prototype.setClientId=R.prototype.ic;R.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.A.bind(this);this.setEnabled(!0);return!0};R.prototype.enable=R.prototype.enable;
R.prototype.ub=function(a,b,c,d,e){var f=_.Te(window.location.href);a=null!=e&&null!=e.message?e.message:a;var g;if(g=!_.na(this.O)||this.O(f.a,a,b,c,d,e))if(g=this.c){g=Object.keys(this.m);for(var k=100,n=0;n<g.length;++n){var t=g[n];(new RegExp(t)).test(a)&&(k=this.m[t])}if(g=(100*Math.random()).toFixed(6)>=this.o*k/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new Af(this.j,this.F));if(null===this.b)g=!1;else{a:{g=this.b;k=(0,_.fa)();if(g.a.length==g.g)if(g.a[0]<k-36E5)g.a.shift();else{g=!1;break a}g.a.push(k);
zf(g);g=!0}g=!g}g=!g&&this.c}}g&&(g=_.Ta(this.a.g),g.url=f.a,g.type="JavascriptError",g.error_message=a,k="Other",ib?k="Opera":_.jb?k="Internet Explorer":Bb?k="Firefox":Fb?k="Chrome":Gb&&(k="Safari"),g.browser=k,g.browser_version=_.af,g.os=_.db()?"Chrome OS":_.v("Linux")?"Linux":_.cb()?"Windows":_.v("Android")?"Android":$a()?"iPhone":_.v("iPad")?"iPad":_.v("iPod")?"iPod":_.bb()?"Mac":"Unknown",k=_.Oa,n="",_.cb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(k=n.exec(k))?k[1]:"0.0"):ab()?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,
n=(k=n.exec(k))&&k[1].replace(/_/g,".")):_.bb()?(n=/Mac OS X ([0-9_.]+)/,n=(k=n.exec(k))?k[1].replace(/_/g,"."):"10"):_.v("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(k=n.exec(k))&&k[1]):_.db()&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(k=n.exec(k))&&k[1]),g.os_version=n||"",null!=this.a.a&&(g.channel=this.a.a),_.Ia(this.g)||(g.guid=this.g),null!=b&&(g.src=b),null!=c&&(g.line=c),null!=d&&(g.column=d),g.prod=this.a.b,g.ver=this.a.c,c=null!=e?_.Na(e.stack):"",b=Cf(g),_.Ia(a)||(d=c.split("\n"),
-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),Df(this,"https://clients2.google.com/cr/staging_report",b,c),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Na(this.a.a),_.Ia(a)||(f.version=a),Df(this,"https://clients2.google.com/cr/staging_perf",Cf(f)))};R.prototype.reportError=R.prototype.ub;R.prototype.A=function(a,b,c,d,e){this.ub(a,b,c,d,e);null!=this.l&&_.na(this.l)&&this.l(a,b,c,d,e)};
var Cf=function(a){var b="",c;for(c in a)b+=_.Ia(b)?"?":"&",b+=c+"="+encodeURIComponent(a[c]);return b},Df=function(a,b,c,d){d=d||"";var e=_.Ia(d)?{}:{"Content-Type":"text/plain"};_.le(b+c,a.I.bind(a,b),"POST",d,e,6E4,!0)};R.prototype.I=function(a,b){_.ue(b.target)};
var Ef=function(a){Bf.call(this,a);this.O=null;this.b=0};_.r(Ef,Bf);Ef.prototype.xb=function(a){this.O=a;return this};var Ff=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];Ef.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.ce(6E4);_.I(this,a);var b=new _.N(this);_.I(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
Ef.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<Ff.length;++b)if(this.b==Ff[b].age){a=Ff[b].name;break}if(""!=a){b=Gf.test(_.Oa)?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.Te(window.location.href).a;
c="?product="+encodeURIComponent(this.a.b)+"&url="+encodeURIComponent(b);var d=_.Na(this.a.a);_.Ia(d)||(c+="&version="+encodeURIComponent(d));for(d=0;d<a.length;++d)c+="&"+encodeURIComponent(a[d].name)+"="+a[d].value,_.na(this.O)&&this.O(b,a[d].displayName,a[d].value);_.le("https://clients2.google.com/cr/staging_perf"+c,Hf,"POST","",null,6E4,!0)}}};var Hf=function(a){_.ue(a.target)},Gf=/(x86_64|Win64)/;
var If=function(a){_.F.call(this);this.b=new uf(a);this.a={}};_.r(If,_.F);_.ta("webmonitoring.Monitoring",If);If.prototype.ca=function(a){this.b.ca(a);return this};If.prototype.setVersion=If.prototype.ca;If.prototype.qa=function(a){this.b.qa(a);return this};If.prototype.setChannel=If.prototype.qa;If.prototype.mb=function(a){this.b.mb(a);return this};If.prototype.setContext=If.prototype.mb;If.prototype.La=function(){null!=this.a[2]||(this.a[2]=new R(this.b));return this.a[2]}; If.prototype.createJsErrorsReporter=If.prototype.La;
var Jf=function(a){If.call(this,a)};_.r(Jf,If);Jf.prototype.ca=function(a){return Jf.w.ca.call(this,a)};Jf.prototype.qa=function(a){return Jf.w.qa.call(this,a)};Jf.prototype.La=function(){var a=Jf.w.La.call(this);a.c=!0;return a};_.Kf=function(){var a=new Jf("Google_Hangouts_Chrome");a.qa(chrome.runtime.id);a.ca(chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new Ef(a.b));a.a[1].enable();a.La().Ab(!1).yb(100).ob("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
try{
var lp=function(a,b){_.pc(a,null,b,void 0)},mp=function(a){_.A(this,a,"uv_r_hrd",null,null)};_.r(mp,_.w);mp.messageId="uv_r_hrd";
var np=function(a,b){return a.g.get(b)},op=function(a,b){a.j=b;_.G(a,function(){this.j=null},a);_.of(a)},pp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ma(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},qp=function(a,b,c){a=_.B(a,b);return null==a?c:a},rp=function(a){var b=new _.nf;_.pf(b);b.a=new _.gf((0,_.q)(b.D,b),a);b.a.da("*",void 0,void 0);b.c.push(_.sa(_.H,b.a));return b};
var sp=function(a){this.a=a;_.jb||(delete this.a.lpu,delete this.a.ppu)},tp=["cn","tp"],up=function(a,b){if(_.na(document.postMessage)||_.na(window.postMessage)||_.jb&&window.postMessage)var c=1;else if(_.lb)c=2;else{var d;if(d=_.jb){d=!1;try{c=window.opener,window.opener={},d=_.gb(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new sp(d)};_.ta("GTalk_IFrameChannelConfig.build",up);
var vp=function(){},yp=function(a){var b=a.ma,c=function(a){c.w.constructor.call(this,a);var b=this.Z.length;this.a=[];for(var d=0;d<b;++d)this.Z[d].Kc||(this.a[d]=new this.Z[d](a))};_.r(c,b);for(var d=[];a;){if(b=a.ma){b.Z&&pp(d,b.Z);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.na(e[f])&&e[f]!==b){var g=!!e[f].Cb,k=wp(f,e,d,g);(g=xp(f,e,k,g))&&(c.prototype[f]=g)}}a=a.w&&a.w.constructor}c.prototype.Z=d;return c},wp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},xp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.Z[c[0]].prototype[a].apply(this,arguments)}:b[a].Eb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]];if(f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Db?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]];f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].Vb?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var t=this.a[c[f]];e.push(t?t[a].apply(t,d):this.Z[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Eb||b[a].Db||b[a].Vb? e=null:e=zp;return e},zp=function(){return[]};vp.prototype.h=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var Ap=function(a){(a?a:function(){}).Cb=!0};
var Bp=function(){};_.r(Bp,vp);Bp.prototype.b=function(a){return a};Ap(Bp.prototype.b);Bp.prototype.g=function(){return!0};Ap(Bp.prototype.g);var Cp=function(a){_.A(this,a,0,null,null)};_.r(Cp,_.w);var Dp=function(a,b){var c=new Cp;_.z(c,1,b);_.z(c,2,a);return c},Ep=Dp("?",0),Fp=Dp("q",1),Gp=Dp("<",2),Hp=Dp(">",3),Ip=Dp("~",4),Jp=Dp("s",5),Kp={pc:Ep,xc:Fp,rc:Gp,sc:Hp,qc:Ip,yc:Jp};var Lp=function(a){_.A(this,a,"h_cc",null,null)};_.r(Lp,_.w);var Mp=function(a){_.A(this,a,0,null,null)};_.r(Mp,_.w);var Np=function(a){_.A(this,a,0,null,null)};_.r(Np,_.w);var Op=function(a){_.A(this,a,0,null,null)};_.r(Op,_.w);var Pp=function(a){_.A(this,a,0,null,null)};_.r(Pp,_.w);Lp.messageId="h_cc";var Qp=function(a,b){_.z(a,3,b)},Rp=function(a,b){_.z(a,4,b)},Sp=function(a,b){_.z(a,11,b)};
var Tp=function(a){_.A(this,a,"ci:ec",null,null)};_.r(Tp,_.w);Tp.messageId="ci:ec";var Up=function(a){return this.hb.h(a)};var Vp=function(){this.a=window.document||{cookie:""}};_.h=Vp.prototype;_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("C`"+a);if(/[;\r\n]/.test(b))throw Error("D`"+b);_.m(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.fa)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.Ja)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.m(this.get(a));this.set(a,"",0,b,c);return d};_.h.X=function(){return Wp(this).keys};_.h.S=function(){return Wp(this).values};_.h.clear=function(){for(var a=Wp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var Wp=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.Ja)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Xp=function(a,b){if(!this.hb){for(var c=this.constructor;c&&!c.ma;)c=c.w&&c.w.constructor;c.ma.sb||(c.ma.sb=yp(c));this.hb=new c.ma.sb(this);this.h||(this.h=Up)}var d=this.hb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ga(d,"https://talkgadget.google.com/talkgadget/")){c=(new Vp).get("WCSDBG","");c=c.split(";")[0];c=c.split("|")[0];var e=["plus.google.com"],f=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<c.length&&!_.Ba(e,c)&&f.test(c)&&(d=_.Te(d),d=_.Te("https://"+
c+d.a).toString())}this.g=d;this.c=b||new Tp;a.notificationsOnly&&_.z(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(b=np(new _.P(window.location.href),"authuser"),null!=b&&(this.b=b));this.o=a.clientUrl||"notifierclient";b=np(_.Te(this.o),"authuser");null!=b&&(this.b=b);this.ab=a.propertyName||"Google Talk";this.I=a.cssUrl;this.locale=a.locale;this.j=a.debug;this.Ja=a.userJid;this.Ga=a.uiVersion;this.Nb=null!=a.rosterExpanded?a.rosterExpanded:!0;this.W=a.hostLogMinValue;this.wa=a.hideChat;
this.Fb=a.refresh;this.P=a.hideProfileCard;this.V=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.N=a.hideRecentConversations;this.L=a.hideOTR;this.bb=a.hostServerMessageCallback||!1;this.ba=a.isCentralRoster;this.gb=a.isFullFrame||!1;this.Jb=a.rosterClass||"talk_roster";this.Ob=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.va=a.parentToken;_.m(a.isRtl)||_.Mc.test(this.locale);
this.l=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var g in Kp)b.push(_.D(Kp[g]))}this.D=a.entityId;this.Ha=a.useQuasarPanels||!1;this.silent=a.silent||!1;this.fb=a.ignoreCentralRoster||!1;this.Ib=a.lazy||!1;this.Na=a.handleProfileLinks||!1;this.ga=a.hostSettings;this.m=a.screen;this.A=a.docsConfig;this.Hb=a.jsmode;this.ua=a.moleWidth;this.ta=a.moleHeight;this.sa=a.minimizedMoleHeight||36;this.Qb=a.derp;this.Fa=window.location.protocol+"//"+window.location.host;this.C="";this.K=a.optOutAllowed;
this.M=a.legacyTalkSignedIn;this.Ia=a.useSpareMole;this.F=a.conversationId};Bp.w||_.r(Bp,vp);Xp.ma=Bp;
var Zp=function(a){var b={},c=_.Lb(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.y(a,2)&&27!=_.y(a,2)&&(d="http://"));b.clientBaseUrl=d+c+"/webchat/u/"+_.Lb(a,8,"0")+"/";b.clientUrl="load";b.authUser=_.Lb(a,8,"0");b.propertyName=Yp(_.y(a,2));b.locale=_.y(a,4);b.hideProfileCard=!0;b.parentToken=_.y(a,3);b.isRtl=qp(a,6,!1);b.lazy=qp(a,7,!1);b.entityId=_.y(a,9);b.hostSettings=_.y(a,5);b.jsmode=_.y(a,11);b.isFullFrame=qp(a,13,!1);b.rosterId=_.Lb(a,12,"talk_roster");
b.rosterIframeId=_.Lb(a,12,"talk_roster");b.rosterIframeIdB=_.Lb(a,15,"gtn-roster-iframe-id-b");b.derp=!!qp(a,16,!1);c=_.C(a,Pp,14);null!=c&&(b.isCentralRoster=qp(c,1,!1),b.useQuasarPanels=qp(c,2,!1));c=_.C(a,Mp,10);null!=c&&(b.moleManagerLeftMargin=_.y(c,1),b.moleManagerMiddleMargin=_.y(c,2),b.moleManagerRightMargin=_.y(c,3),b.moleManagerNoMoleAreaMargin=_.y(c,4),b.moleManagerBoundingElementId=_.y(c,5),b.moleWidth=_.y(c,6),b.moleHeight=_.y(c,7),b.minimizedMoleHeight=_.y(c,8));c=_.C(a,Np,18);null!=
c&&(b.optOutAllowed=qp(c,1,!0),d=_.C(c,Op,3),null!=d&&(b.legacyTalkSignedIn=qp(d,1,!0)),c=_.B(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Tp;_.z(c,2,!0);_.z(c,1,!0);_.z(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=qp(a,17,!1);b.conversationId=_.y(a,19);return b},Yp=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";
case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},$p=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Te(a),d=c.a;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.a="/u/"+b+d;return c.toString()}return a};
var aq=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.g=new _.N(this);_.I(this,this.g);var f=_.Oa;d=new _.P(a.g+a.o);qp(a.c,2,!1)||(_.Q(d,"ts","0"),_.Q(d,"re",a.Nb),_.Q(d,"ref",a.Fb));_.Q(d,"client","sm");_.Q(d,"prop",a.ab);_.Q(d,"nav","true");_.Q(d,"fid",a.a);a.j&&_.Q(d,"debug",a.j);_.Q(d,"os",_.nb);_.Q(d,"stime",c);a.wa&&_.Q(d,"hc",a.wa);for(c=0;c<tp.length;++c);b=_.dd(b.a);_.Q(d,"xpc",b);_.Q(d,"ec",_.dd(_.D(a.c)));a.m&&_.Q(d,"screen",a.m);-1!=f.indexOf("MSIE")&&_.Q(d,
"ua",f);a.va&&_.Q(d,"pvt",a.va);a.bb&&_.Q(d,"hsmc","true");_.m(a.W)&&_.Q(d,"logl",a.W);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.Q(d,"href",b.join("?")));b=new _.P(window.location.href);"false"==np(b,"uacheck")&&_.Q(d,"uacheck",!1);(f=a.Hb)&&_.Q(d,"jsmode",f);(f=np(b,"cssmode"))&&_.Q(d,"cssmode",f);(f=np(b,"convid"))&&_.Q(d,"convid",f);if(f=b.g.S("convp"))_.la(f)||(f=[String(f)]),_.Ze(d.g,"convp",f);(f=np(b,"smexp"))&&_.Q(d,"smexp",
f);f=b.g.S("mods");a.Ib&&f.push("lazy");e&&(f=_.Ea(f,e));0<f.length&&_.Q(d,"mods",f.join(","));if(!a.g||0>a.g.indexOf("/u/"))(e=np(b,"authuser"))?_.Q(d,"authuser",e):null!=a.b&&_.Q(d,"authuser",a.b);e=np(b,"eid");_.Ia(_.Na(e))||_.Q(d,"eid",e);_.Ia(_.Na(this.a.D))||_.Q(d,"eid",this.a.D);null!=this.a.l&&_.Q(d,"pos",this.a.l);_.m(a.Ga)&&_.Q(d,"uiv",this.a.Ga);a.I&&_.Q(d,"css",a.I);e=a.locale||np(b,"hl");null!=e&&_.Q(d,"hl",e);_.m(a.Ja)&&_.Q(d,"uj",a.Ja);null!=a.P&&_.Q(d,"hpc",a.P);null!=a.V&&_.Q(d,"hsm",
a.V);null!=a.T&&_.Q(d,"hro",a.T);null!=a.N&&_.Q(d,"hrc",a.N);null!=a.L&&_.Q(d,"hotr",a.L);null!=a.ba&&_.Q(d,"pop",a.ba);_.Q(d,"pal","1");null!=a.Ha&&_.Q(d,"uqp",a.Ha);null!=a.K&&_.Q(d,"gooa",a.K);null!=a.M&&_.Q(d,"gltsi",a.M);null!=a.Ia&&_.Q(d,"gusm",a.Ia);null!=a.silent&&_.Q(d,"sl",a.silent);a.fb&&_.Q(d,"icr","1");a.Na&&_.Q(d,"hpl","1");a.ga&&_.Q(d,"hs",a.ga);a.A&&_.Q(d,"dc",_.dd(_.D(a.A)));null!=a.ua&&_.Q(d,"molew",a.ua);null!=a.ta&&_.Q(d,"moleh",a.ta);null!=a.sa&&_.Q(d,"mmoleh",a.sa);a.Qb&&_.Q(d,
"derp","1");a.C&&_.Q(d,"fcho",a.C);null!=a.Fa&&_.Q(d,"two",a.Fa);null!=a.F&&_.Q(d,"convid",a.F);_.Q(d,"host","1");_.Q(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.fa)()).toString(36));this.c=d.toString()};_.r(aq,_.F);aq.prototype.install=function(a,b){bq(this,a,b,_.ja)};
var bq=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Jb,a.b.body.appendChild(e));a=(0,_.q)(function(){var a="";this.a.gb||(a="height:400px");var b=_.ad(new _.$c(this.b),"IFRAME");_.Yc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true",allow:"microphone *; autoplay *"});_.Wc("talk_loading_msg",e)||_.Zc(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.xe(this.g,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});k.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var cq=function(a){var b=_.Ue(_.y(a,2),"/webchat/extension-start");_.y(a,5)&&_.Q(b,"e",_.y(a,5));return new _.jc(function(a,d){_.le(b,function(b){_.ue(b.target)||d();try{var c=b.target;try{var e=c.a?c.a.responseText:""}catch(n){e=""}var k=JSON.parse(e);a(new _.Ce(k))}catch(n){d(n.message)}})})};
var eq=function(){var a=this;_.N.call(this);_.O("Starting ...");this.listen(window,"unload",this.$);this.b=new _.ye(JSON.parse(decodeURI(location.hash.substr(1))));this.a=rp(_.y(this.b,1));_.I(this,this.a);this.g=new _.nf;_.I(this,this.g);lp(cq(this.b).then(function(b){return dq(a,b)}),function(a){_.O("Failed to start : %s.",a||"")})},fq;_.r(eq,_.N);
var dq=function(a,b){if(!a.G&&(a.a.sendMessage(b),_.y(b,1))){var c=new Lp,d=_.Te(_.y(a.b,2)),e=d.b;null!=d.c&&(e+=":"+d.c);_.z(c,1,e);_.z(c,2,23);_.z(c,13,!0);_.z(c,17,!0);Qp(c,_.y(b,1));Sp(c,_.y(a.b,4));Rp(c,_.y(a.b,3)||"en");b=Zp(c);var f=new Xp(b,b.endpointConfig);f.g=$p(f.g,f.b);f.C=location.origin;f.a="gtn-roster-iframe-id-q";b=up(f.g,f.a);b=new aq(f,b,(0,_.fa)(),window.document);_.I(a,b);bq(b,f.Ob,function(){},function(){_.sf(a.g,document.getElementById(f.a).contentWindow,"31ACFC0_","google.com"); op(a.g,a.a);op(a.a,a.g);a.a.sendMessage(new mp)})}};_.ta("default_host._DumpException",function(a){return console.error(a.stack)});_.Kf();if(!fq||fq.G)fq=new eq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
